/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/new-list`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/ai` | `/ai`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/templates` | `/templates`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/email` | `/email`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/otp` | `/otp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/profile-setup` | `/profile-setup`; params?: Router.UnknownInputParams; } | { pathname: `/dev/components`; params?: Router.UnknownInputParams; } | { pathname: `/dev/design-tokens`; params?: Router.UnknownInputParams; } | { pathname: `/invite/[token]`, params: Router.UnknownInputParams & { token: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/new-list`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/ai` | `/ai`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/templates` | `/templates`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/email` | `/email`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/otp` | `/otp`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/profile-setup` | `/profile-setup`; params?: Router.UnknownOutputParams; } | { pathname: `/dev/components`; params?: Router.UnknownOutputParams; } | { pathname: `/dev/design-tokens`; params?: Router.UnknownOutputParams; } | { pathname: `/invite/[token]`, params: Router.UnknownOutputParams & { token: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/new-list${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/ai${`?${string}` | `#${string}` | ''}` | `/ai${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/templates${`?${string}` | `#${string}` | ''}` | `/templates${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/email${`?${string}` | `#${string}` | ''}` | `/email${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/otp${`?${string}` | `#${string}` | ''}` | `/otp${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/profile-setup${`?${string}` | `#${string}` | ''}` | `/profile-setup${`?${string}` | `#${string}` | ''}` | `/dev/components${`?${string}` | `#${string}` | ''}` | `/dev/design-tokens${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/new-list`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/ai` | `/ai`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/templates` | `/templates`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/email` | `/email`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/otp` | `/otp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/profile-setup` | `/profile-setup`; params?: Router.UnknownInputParams; } | { pathname: `/dev/components`; params?: Router.UnknownInputParams; } | { pathname: `/dev/design-tokens`; params?: Router.UnknownInputParams; } | `/invite/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/invite/[token]`, params: Router.UnknownInputParams & { token: string | number; } };
    }
  }
}
